// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4l4-gZJNsElJBSpmnRLsHlbY90ZAN2l4',
    appId: '1:146476586304:web:ee02293a2f53df853e16a5',
    messagingSenderId: '146476586304',
    projectId: 'healthy-app-5dab0',
    authDomain: 'healthy-app-5dab0.firebaseapp.com',
    databaseURL: 'https://healthy-app-5dab0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthy-app-5dab0.appspot.com',
    measurementId: 'G-FV3811M567',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrffUdDlpNnybmw_hSwW6ybVu_ZDv8LY',
    appId: '1:146476586304:android:f1786af1f10923283e16a5',
    messagingSenderId: '146476586304',
    projectId: 'healthy-app-5dab0',
    databaseURL: 'https://healthy-app-5dab0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthy-app-5dab0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvcSNFeLO-SM3qSfU9NAbPXjuWMCWaiZI',
    appId: '1:146476586304:ios:e88e82c6e6bb6fb03e16a5',
    messagingSenderId: '146476586304',
    projectId: 'healthy-app-5dab0',
    databaseURL: 'https://healthy-app-5dab0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthy-app-5dab0.appspot.com',
    androidClientId: '146476586304-63o771e9fvh6h6d6bq2r9kp4hqjdu277.apps.googleusercontent.com',
    iosClientId: '146476586304-ddjte3dtqqq9p3kv1dpt5gncflgecvk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvcSNFeLO-SM3qSfU9NAbPXjuWMCWaiZI',
    appId: '1:146476586304:ios:a8a6d8fc6fc19d293e16a5',
    messagingSenderId: '146476586304',
    projectId: 'healthy-app-5dab0',
    databaseURL: 'https://healthy-app-5dab0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthy-app-5dab0.appspot.com',
    androidClientId: '146476586304-63o771e9fvh6h6d6bq2r9kp4hqjdu277.apps.googleusercontent.com',
    iosClientId: '146476586304-5hlh6ef5r8csgbev5n5r0595uv2l1s4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyAppFlutter.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4l4-gZJNsElJBSpmnRLsHlbY90ZAN2l4',
    appId: '1:146476586304:web:ec04de854de1102b3e16a5',
    messagingSenderId: '146476586304',
    projectId: 'healthy-app-5dab0',
    authDomain: 'healthy-app-5dab0.firebaseapp.com',
    databaseURL: 'https://healthy-app-5dab0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthy-app-5dab0.appspot.com',
    measurementId: 'G-Z5FXKH7ZQG',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA4l4-gZJNsElJBSpmnRLsHlbY90ZAN2l4',
    appId: '1:146476586304:web:077fd2a5b19525653e16a5',
    messagingSenderId: '146476586304',
    projectId: 'healthy-app-5dab0',
    authDomain: 'healthy-app-5dab0.firebaseapp.com',
    databaseURL: 'https://healthy-app-5dab0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthy-app-5dab0.appspot.com',
    measurementId: 'G-XVJBNXLVX4',
  );
}
